sonar.projectKey=namanhle-gif_namanhle-gif-prj301-assignment-he2041-dan-branch
sonar.organization=namanhle-gif


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=namanhle-gif-PRJ301_ASSIGNMENT_HE2041-DAN_BRANCH
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
